spring:
    application:
        name: chatapp
    data:
        mongodb:
            username:
            password:
            host: localhost
            port: 27017
            database: chat_app
            authentication-database: admin

